name: Feature Request
description: Propose a new feature or improvement
labels: [ "enhancement" ]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this for?
      options:
        - logger
        - new package
        - other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What is currently missing or painful?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you'd like to see added or changed.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought of?
    validations:
      required: false
